#!/bin/bash
#TO START WITH A FOLDER CALLED <hadoop> must be made in the home directory and this
# bas script should be ran in </home/hadoop/>
#wget http://archive.apache.org/dist/hadoop/common/hadoop-2.8.5/hadoop-2.8.5.tar.gz
#tar -xzvf hadoop-2.8.5.tar.gz

echo "export HADOOP_HOME=/home/hadoop/hadoop-2.8.5
export HADOOP_INSTALL=\$HADOOP_HOME
export HADOOP_COMMON_HOME=\$HADOOP_HOME
export HADOOP_MAPRED_HOME=\$HADOOP_HOME
export HADOOP_HDFS_HOME=\$HADOOP_HOME
export HADOOP_COMMON_LIB_NATIVE_DIR=\$HADOOP_HOME/lib/native
export YARN_HOME=\$HADOOP_HOME
export PATH=\$PATH:\$HADOOP_HOME/sbin:\$HADOOP_HOME/bin
export HADOOP_OPTS=\"-Djava.library.path=\$HADOOP_HOME/lib/native\"" >> /home/hadoop/.bashrc


source ~/.bashrc




echo "export JAVA_Home=/usr/lib/jvm/java-8-oracle/jre
export HADOOP_CONF_DIR=\${HADOOP_CONF_DIR:-\"/home/hadoop/hadoop-2.8.5/etc/hadoop\"}" >> /home/hadoop/hadoop-2.8.5/etc/hadoop/hadoop-env.sh


echo "
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<?xml-stylesheet type=\"text/xsl\" href=\"configuration.xsl\"?>
<!--
  Licensed under the Apache License, Version 2.0 (the \"License\");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an \"AS IS\" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License. See accompanying LICENSE file.
-->

<!-- Put site-specific property overrides in this file. -->



<configuration>
<property>
<name>fs.defaultFS</name>
<value>hdfs://localhost:9000</value>
<description>Parent directory for other temporary directories.</description>
</property>
<property>
<name>hadoop.tmp.dir</name>
<value>/home/hadoop/hadooptempdata</value>
<description>The name of the default file system. </description>
</property>
</configuration>
" > /home/hadoop/hadoop-2.8.5/etc/hadoop/core-site.xml


